spring:
  datasource:
    url: jdbc:h2:mem:screenmatch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

api:
  url: https://www.omdbapi.com/?apikey=${OMDB_API_KEY}&t={titulo}
  security:
    token:
      secret: ${JWT_SECRET:batman batman batman}